{{- if .Values.persistence.serverKeys.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "sshd.fullname" . }}-server-keys
  labels:
    app: {{ template "sshd.name" . }}
    chart: {{ template "sshd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.persistence.serverKeys.size }}"
  storageClassName: "{{ .Values.persistence.serverKeys.storageClassName }}"
{{- end }}
