{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "sshd.fullname" . }}
  labels:
    app: {{ template "sshd.name" . }}
    chart: {{ template "sshd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.persistence.size }}"
  storageClassName: "{{ .Values.persistence.storageClassName }}"
{{- end }}
